# module ref: https://github.com/citrix/citrix-adc-ansible-modules

- hosts: citrix_adc
  vars:
    nsip: 192.168.24.80
    nitro_user: nsroot
    nitro_pass: nsroottt
    ldap_svc1_ip: 192.168.24.50
    ldapvs_ip: 192.168.24.156
    ldaps_basedn: dc=trickyjoe,dc=local
    ldaps_binddn: svc.netscaler@trickyjoe.local
    ldaps_bindpass: password

  gather_facts: no
  collections:
    - citrix.adc

# ldaps service
  tasks:
    - name: setup ldaps monitor
      delegate_to: localhost
      citrix_adc_lb_monitor:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        state: present
        monitorname: mon_ldaps
        type: LDAP
        basedn: "{{ ldaps_basedn }}"
        binddn: "{{ ldaps_binddn }}"
        password: "{{ ldaps_bindpass }}"
        secure: yes
    
    - name: Setup ldaps service group
      delegate_to: localhost
      citrix_adc_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        servicegroupname: svcgrp_ldaps_636_ansible
        servicetype: TCP
        servicemembers:
            mode: exact
            attributes:
              - ip: "{{ ldap_svc1_ip }}"
                port: 636

        monitor_bindings:
            mode: exact
            attributes:
              - monitor_name: mon_ldaps

    # Citrix ADC ldaps service

    - name: Create vserver
      delegate_to: localhost
      citrix_adc_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no

        state: present

        name: vsrv_ldaps_636_ansible
        servicetype: TCP
        timeout: 12
        ipv46: "{{ ldapvs_ip }}"
        port: 636
        servicegroupbindings:
            - servicegroupname: svcgrp_ldaps_636_ansible
