- hosts: azwin10
  gather_facts: false
    
  tasks:

  - name: Run a powershell command
    win_shell: |
      New-Item -Path C:\temp -ItemType Directory
      New-Item -Path C:\temp\ansible -ItemType Directory
      write-host hello-mate >> c:\temp\ansible\test.txt

  - name: Run a command under cmd
    win_shell: echo ansible test >> C:\temp\test.txt && echo still here >> c:\temp\test.txt
    args:
      executable: cmd.exe

  - name: Install notepad-plus-plus
    win_package:
      path: https://notepad-plus-plus.org/repository/7.x/7.0/npp.7.Installer.x64.exe
      product_id: Notepad++
      arguments: /S
      state: present
      
  - name: reg key
    win_regedit:
      path: HKLM:\Software\TTLAB
      name: hello
      data: world
      
  - name: dword reg key
    win_regedit:
      path: HKLM:\Software\TTLAB
      name: hellod
      data: 1
      type: dword
  
#  - name: join Azure AD DS domain
#    win_domain_membership:
#      dns_domain_name: "{{ adds_fqdn }}"
#      domain_admin_user: "{{ adds_admin_user }}"
#      domain_admin_password: "{{ adds_admin_pass }}"
#      state: domain
#    register: domain_state
    
#  - win_reboot:
#    when: domain_state.reboot_required
  
