- hosts: wintel
  gather_facts: false
  tasks:

#  - name: Add Azure PowerShell Module
#    win_psmodule:
#      name: AZ
#      state: present

  - name: Run a command under cmd
    win_shell: echo this is a test >> %temp%\ansibletest.txt && echo another test >> %temp%\ansibletest.txt
    args:
      executable: cmd.exe

  - name: Run multiple powershell commands
    win_shell: |
      New-Item -Path $env:temp\ansibletest -ItemType Directory
      write-host hello-again >> $env:temp\ansibletest\ansibletest.txt

  - name: Install notepad-plus-plus
    win_package:
      path: https://notepad-plus-plus.org/repository/7.x/7.0/npp.7.Installer.x64.exe
      product_id: Notepad++
      arguments: /S
      state: present
     
  - name: citrix workspace
    win_package:
      path: c:\temp\citrixworkspaceapp.exe
      product_id: CitrixOnlinePluginPackWeb
      arguments: /silent /noreboot /autoupdatecheck=disabled /enableCEIP=False STORE0=https://storefront.lab.local/store;On;Store
      state: present
      
