- hosts: azws2019
  gather_facts: false
  vars:
    adds_fqdn: ttlab.local
    adds_admin_user: ttwinrm@ttlab.local 
    adds_admin_pass: Ansiblem@nage
    adds_ou_path: "OU=SessionHosts,OU=Citrix,OU=Infra,DC=ttlab,DC=local"
    appinstall_path: \\WS2019ADDS01\applications
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ adds_admin_user }}"
    ansible_become_password: "{{ adds_admin_pass }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only    
    
  tasks:

  - name: join AD DS domain
    win_domain_membership:
      dns_domain_name: "{{ adds_fqdn }}"
      domain_admin_user: "{{ adds_admin_user }}"
      domain_admin_password: "{{ adds_admin_pass }}"
      domain_ou_path: "{{ adds_ou_path }}"
      state: domain
    register: domain_state
    
  - win_reboot:
    when: domain_state.reboot_required

  - name: Enable RDS win feature  
    win_feature:
      name: RDS-RD-Server
      state: present
      include_management_tools: False

  - name: reboot pre-dependency installations
    win_reboot:
      
# Install runtimes and dependencies

#  - name: map a drive to application installation source
#    win_mapped_drive:
#      letter: M
#      path: \\WS2019ADDS01\applications

#  - name: run a command using a working directory   
#    win_shell: cmd /c Install-VisualCRedist.CMD
#    args:
#      chdir: m:\applications\Microsoft Visual C++ 2015 Redistributable x64

#  - name: Run Visual C++ 2008 Redistributable x86    
#    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2008 Redistributable x86\Install-VisualCRedist.CMD"
    
#  - name: Run Visual C++ 2008 Redistributable x64   
#    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2008 Redistributable x64\Install-VisualCRedist.CMD"

#  - name: Run Visual C++ 2010 Redistributable x86
#    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2010 Redistributable x86\Install-VisualCRedist.CMD"

#  - name: Run Visual C++ 2010 Redistributable x64    
#    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2010 Redistributable x64\Install-VisualCRedist.CMD"

#  - name: Run Visual C++ 2012 Redistributable x86
#    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2012 Redistributable x86\Install-VisualCRedist.CMD"

#  - name: Run Visual C++ 2012 Redistributable x64    
#    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2012 Redistributable x64\Install-VisualCRedist.CMD"

  - name: Run Visual C++ 2013 Redistributable x86
    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2013 Redistributable x86\Install-VisualCRedist.CMD"

  - name: Run Visual C++ 2013 Redistributable x64    
    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2013 Redistributable x64\Install-VisualCRedist.CMD"

  - name: Run Visual C++ 2015 Redistributable x86
    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2015 Redistributable x86\Install-VisualCRedist.CMD"

  - name: Run Visual C++ 2015 Redistributable x64    
    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2015 Redistributable x64\Install-VisualCRedist.CMD"    

  - name: Run Visual C++ 2015 Redistributable x86   
    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2015 Redistributable x86\Install-VisualCRedist.CMD"  

  - name: Run Visual C++ 2017 Redistributable x64    
    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2017 Redistributable x64\Install-VisualCRedist.CMD"    

  - name: Run Visual C++ 2017 Redistributable x86    
    win_shell: cmd /c "\\WS2019ADDS01\applications\Microsoft Visual C++ 2017 Redistributable x86\Install-VisualCRedist.CMD"  

  - name: Reboot post dependency installations
    win_reboot:

# Install hosting platform tools

#  - name: Install VMware Tools
#    win_shell: cmd /c "\\WS2019ADDS01\applications\VMware Tools 10.\Install-VMwareTools-x64.CMD"

# OS Customisation
      
#  - name: reg key example
#    win_regedit:
#      path: HKLM:\Software\TTLAB
#      name: hello
#      data: world
      
#  - name: dword reg key example
#    win_regedit:
#      path: HKLM:\Software\TTLAB
#      name: hellod
#      data: 1
#      type: dword


#  - name: Run a powershell command
#    win_shell: |
#      New-Item -Path C:\temp -ItemType Directory
#      New-Item -Path C:\temp\ansible -ItemType Directory
#      write-host hello-mate >> c:\temp\ansible\test.txt

#  - name: Run a command under cmd
#    win_shell: echo ansible test >> C:\temp\test.txt && echo still here >> c:\temp\test.txt
#    args:
#      executable: cmd.exe

# Citrix components

  - name: Run Install Citrix VDA
    win_shell: cmd /c "\\WS2019ADDS01\applications\Citrix XenDesktop 2012\Install-XenDesktopVDA-ServerMaster.cmd"    

#  - name: Install Citrix VDA
#    win_package:
#      path: \\WS2019ADDS01\applications\Citrix XenDesktop 2012\x64\XenDesktop Setup\XenDesktopVDASetup.exe
#      product_id: '{C344C994-94D2-45EC-AD93-0EBBA1E9D5DD}'
#      arguments: /QUIET /NOREBOOT /COMPONENTS "VDA" /CONTROLLERS "ddc01.trickyjoe.local,ddc02.trickyjoe.local" /ENABLE_FRAMEHAWK_PORT /ENABLE_HDX_PORTS /ENABLE_REAL_TIME_TRANSPORT /ENABLE_REMOTE_ASSISTANCE /EXCLUDE "PERSONAL VDISK,CITRIX UNIVERSAL PRINT CLIENT" /MASTERIMAGE /OPTIMIZE
#      state: present
#      log_path: c:\XenDesktopVDASetup.log

  - name: Reboot post VDA installations
    win_reboot:


# Install applications

  - name: Install notepad-plus-plus
    win_package:
      path: https://notepad-plus-plus.org/repository/7.x/7.0/npp.7.Installer.x64.exe
      product_id: Notepad++
      arguments: /S
      state: present
