---
azws2019:
  hosts:
    azws201901:
      ansible_host: 20.56.188.211
    azws201902:
      ansible_host: 20.56.188.212
  vars:
      ansible_user: labadmin
      ansible_password: +CkRPx3CP1wCVg*fvnj_
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore

azwin10:
  hosts:
    azwin1001:
      ansible_host: 20.76.24.23
    azwin1002:
      ansible_host: 20.76.24.24
  vars:
      ansible_user: labadmin
      ansible_password: +CkRPx3CP1wCVg*fvnj_
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore
